### PR TITLE
add ie 11 test with my machine info

### PR DESCRIPTION
**Pull request by qpitlove**
(window7, ie11 korean version)
- ignore node_modules

### CODE REVIEW

**Comment by srfrnk** [comment]
Instead of this:
~~~
[/\bMSIE ([\d\.]+\w?)\b/, /\bTrident.*rv:([\d\.]+\w?)\b/]
~~~

Why not use the following?
~~~
/(?:\bMSIE ([\d\.]+\w?)\b) | (?:\bTrident.*rv:([\d\.]+\w?)\b)/
~~~

This way you don't need an array nor the code that handles it.

**Comment by qpitlove** [comment]
I tried to aply your suggestion code, but test was failed in IE11 (Trident version)
```
ட ng-device-detector 
  ட with user-agent 
    ட Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.3; rv:11.0) like Gecko 
      ட ✘ should detect browser version= 11.0 FAILED
        Expected undefined to be '11.0'.
            at /Volumes/Macintosh_HD2/irteam/IdeaProjects/ng-device-detector/test/unit.js:64
```

**Comment by srfrnk** [comment]
You're right.... there's a problem there... I will sit on it tomorrow - hopefully I can come up with a clean solution. Will let you know when I had some time to think about it.

**Comment by qpitlove** [comment]
Thanks you.
let me know if you have solution.
I'll watching your repository. ^^

**Pull request closed without merging**
