### PR TITLE
regex update for excluding windows phone

### PR DESCRIPTION
**Pull request by vinaynaidu**
There's a [JsBin Demo](http://jsbin.com/kexusi/9/) to test the regex / output for the raw UA string as provided by the Lumia 930. 

To test on origin UA strings, [JsBin can be edited](http://jsbin.com/kexusi/9/edit); the line `//var ua = $window.navigator.userAgent;` has been left in commented.

[Review on Reviewable](https://reviewable.io/reviews/srfrnk/ng-device-detector/33)

### CODE REVIEW

**Comment by vinaynaidu** [comment]
Hi, there seems to be some dependency errors.. let me know if I need to do anything, thanks

**Comment by srfrnk** [comment]
try again now - i fixed the dependencies. you will probably need to merge from master.

**Comment by vinaynaidu** [comment]
That seems to have worked, thanks.

**Comment by srfrnk** [comment]
that's great to hear - just one thing - can you add tests for the changes you made?

**Comment by vinaynaidu** [comment]
Good call, Introduced a new constant `WINDOWS_PHONE_8_1: "windows-phone-8-1"` for picking up the right version, and have added tests on both utils and unit.

**Comment by srfrnk** [comment]
great work :)

**Comment by vinaynaidu** [comment]
Thanks for the merge!
Just one thing - the min.js hasn't been updated with new constant; I completely forgot about it. Should I updated it and send another PR?

**Comment by srfrnk** [comment]
yup

**Pull request merged**
